// Generated by Wrangler by running `wrangler types`

interface Env {
	HF_API_TOKEN: string;
	CF_ACCOUNT_ID: string;
	CF_AI_GATEWAY_ID: string;
	SLACK_SIGNING_SECRET: string;
	SLACK_BOT_TOKEN: string;
	SLACK_LOGGING_LEVEL: "DEBUG" | "INFO" | "WARN" | "ERROR" | undefined;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
}
