// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  DB: D1Database
  VECTORIZE: VectorizeIndex
  // Hugging Face + AI Gateway
  HF_API_TOKEN: string
  CF_ACCOUNT_ID: string
  CF_AI_GATEWAY_ID: string
}
