#:schema node_modules/wrangler/config-schema.json
name = "slack-emoji-recommend"
main = "src/index.ts"
compatibility_date = "2024-11-1"
compatibility_flags = ["nodejs_compat"]

[[vectorize]]
binding = "VECTORIZE"
index_name = "emoji-embeddings"

[[d1_databases]]
binding = "DB"
database_name = "emoji-recommend"
database_id = "0efc6aaf-fdee-4133-9ff1-aa298a953d6d"

[observability]
enabled = true
head_sampling_rate = 1
